on:
  pull_request:
    branches:
      - "main"
      - "feature/*"
      - "feature_engineering"
      - "create_actions_workflow"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true 

      - name: Cache the virtualenv
        uses: actions/cache@v4
        id: poetry-cache
        with:
          path: .venv                      
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install --with ci --no-interaction --no-root

      - name: Run Unit Tests
        run: poetry run pytest src

      - name: Run mypy
        run: poetry run mypy src

      - name: Run pylint
        run: poetry run pylint --rcfile=.pylintrc src

      - name: Run coverage
        run: |
          poetry run coverage run -m pytest src 
          poetry run coverage report 
          poetry run coverage html

      - name: Run pyinstrument profiler
        run: make profile-all

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      - name: Upload pyinstrument reports
        uses: actions/upload-artifact@v4
        with:
          name: pyinstrument-reports
          path: pyinstrument_*.html

      - name: Prepare Pages directory
        run: |
          mkdir pages
          mkdir pages/coverage
          mkdir pages/profiler
          cp -r htmlcov/* pages/coverage/
          cp -r pyinstrument_*.html pages/profiler/ || true

      - name: Deploy Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: pages

